name: vprofile-app-actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: my-test-repo
  EKS_CLUSTER: eks-cluster
jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Maven test
        uses: mvn test
      - name: checkstyle
        uses: mvn checkstyle:checkstyle
      
    #Java set up for SonarQube Scanner
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
    #SonarQube Scanner setup
      - name: SoanrQube Setup
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.host.url=${{secrets.SONAR_URL}}
          -Dsonar.login=${{secrets.SONAR_TOKEN}}
          -Dsonar.organization=${{secrets.SONAR_ORGANIZATION}}
          -Dsonar.projectKey=${{secrets.SONAR_PROJECT_KEY}}
          -Dsonar.sources=src/
          -Dsonar.junit.reportsPath=target/surefire-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exec  
          -Dsonar.organization=my-organization
          -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result-xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account
     
    #Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }} #OPTIONAL

